// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6-mqT7khsOpPSP7Wv36UbFiS7diVCMs',
    appId: '1:306956796087:android:c2576066c78b95f23dcd32',
    messagingSenderId: '306956796087',
    projectId: 'noteapp-5ed21',
    storageBucket: 'noteapp-5ed21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvUTt60e-LD5efmxi5NLP0cVqLMw4CfU',
    appId: '1:306956796087:ios:73603cd1f240aba93dcd32',
    messagingSenderId: '306956796087',
    projectId: 'noteapp-5ed21',
    storageBucket: 'noteapp-5ed21.firebasestorage.app',
    androidClientId: '306956796087-pl5to72qtn47ar993vfmm20vb1kv4m58.apps.googleusercontent.com',
    iosClientId: '306956796087-07m7iklplaotitbg43hhenj16r9ng6h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

}